require_relative 'tasks/docs'
require_relative 'tasks/desktop-config-lite'
require 'cookstyle'
require 'chefspec'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

desc 'Run Cookstyle linting'
RuboCop::RakeTask.new(:cookstyle) do |task|
  task.options << '--display-cop-names'
  task.options << '--parallel'
end

desc 'Run ChefSpec unit tests'
RSpec::Core::RakeTask.new(:chefspec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
end

namespace :spellcheck do
  task :run do
    sh 'cspell "**/*" "*.md"'
  end

  task :unknown_words do
    sh 'cspell "**/*" "*.md" --wordsOnly --no-summary | sort | uniq'
  end
end

task spellcheck: 'spellcheck:run'

task default: %i(cookstyle chefspec spellcheck)
