version: '2'
services:
  mongodb:
    image: core/mongodb:3.2.10
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''" 
      HAB_LICENSE: "accept"
  national-parks:
    image: jvogt/national-parks:latest
    command: --peer mongodb --bind database:mongodb.default
    environment:
      HAB_LICENSE: "accept"
    ports:
      - 18080:8080